### ISSUE TITLE
I can't find the package "collagen"

### ISSUE THREAD

**Issue by misty-rain-q** [Oulu-IMEDS/CLIMATv2#1]
I can't find the packeage collagen by pip install or conda install, could you tell me how to install it?

**Comment by hoanghng** [comment]
The collagen can be found at https://github.com/MIPT-Oulu/Collagen.
After download the library, you run
```bash
cd Collagen
pip install -e .
```

**Comment by misty-rain-q** [comment]
> 
thanks
