### ISSUE TITLE
I can't find MOST_OAI_FULL_0_2 data

### ISSUE THREAD

**Issue by misty-rain-q** [Oulu-IMEDS/CLIMATv2#3]
when I do a data prepare for the oai datasets, I run the comands "python ./common/do_split.py" but I can't found png files in the MOST_OAI_FULL_0_2, can you telll me how to get the MOST_OAI_FULL_0_2 data?

**Comment by hoanghng** [comment]
That is the folder containing knee images that are cropped from bilateral knee x-ray images from the OAI dataset. Some samples are shown in Figure 2 of https://arxiv.org/pdf/2210.13889.pdf.

To localize knee centers for the cropping, you can either use BoneFinder (https://bone-finder.com/) or KNEEL (https://github.com/Oulu-IMEDS/KNEEL).
